development:
  adapter: postgresql
  encoding: unicode
  database: solomonsdt_dev
  pool: 5
  host: localhost
  username: postgres
  password: gfhjkm123
  port: 5433
test:
  adapter: postgresql
  encoding: unicode
  database: solomonsdt_test
  pool: 5
  host: localhost
  username: postgres
  password: gfhjkm123
  port: 5433
